name: Generate and build API

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine
          python -m pip install --upgrade PyYAML
      - name: Generate API
        run: |
          sh generate-openapi.sh
          sudo chown -R runner:docker openapi
      - name: Generate MQTT Models
        run: |
          sh generate-mqtt.sh
          sudo chown -R runner:docker mqtt-output
          python asyncapi_generator_cleaning.py --dir mqtt-output
      - name: Move MQTT files into Flotilla package
        run: |
          mkdir ./openapi/src/flotilla_mqtt
          mv ./mqtt-output/* ./openapi/src/flotilla_mqtt/
      - name: Build
        run: |
          python -m build ./openapi --outdir ./build
